name = "render-pinger"
main = "index.js"
compatibility_date = "2025-08-27"

[triggers]
crons = ["*/14 * * * *"]

[vars]
BACKEND_URL = "https://notification-service-focusx-x8ky.onrender.com;https://goal-service-focusx-mym5.onrender.com;https://session-service-focusx-3ia6.onrender.com;https://focusx-user-service-lg70.onrender.com"
