name = "render-pinger"
main = "index.js"
compatibility_date = "2025-08-27"

[triggers]
crons = ["*/14 * * * *"]

[vars]
BACKEND_URL = "https://goal-service-focusx.onrender.com;https://session-service-focusx.onrender.com;https://user-service-focusx-d8o3.onrender.com;https://notification-service-focusx.onrender.com"
