name = "focusx-pinger"
main = "index.js"
compatibility_date = "2025-08-27"

[triggers]
crons = ["*/14 * * * *"]

[vars]
BACKEND_URL = "https://goal-service-focusx-necf.onrender.com;https://session-service-focusx-owi8.onrender.com;https://user-service-focusx-e0au.onrender.com;https://notification-service-focusx-xb7v.onrender.com"
